FROM node:18-alpine
WORKDIR /app

# Instala as dependências
COPY package.json package-lock.json ./
RUN npm install

# Copia o código e realiza o build
COPY . .
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]