version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/DiariasRO.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: diariasro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: